name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H pointlessapi.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@pointlessapi.com << 'EOF'
          cd ~
          ls -l
          git -C pointlessapi pull || git clone https://github.com/weddleben/pointlessapi.git
          cd pointlessapi
          # Publish
          dotnet publish -c Release -r linux-x64 -o /home/ec2-user/pointlessapi/publish
    
          # Move the published files
          sudo mkdir -p /var/www/pointless
          sudo cp -r /home/ec2-user/pointlessapi/publish/* /var/www/pointless/
    
          # Restart the service
          sudo systemctl restart pointless
        EOF
