name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H pointlessapi.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        # SSH
        ssh ec2-user@pointlessapi.com
        cd ~
        git -C pointlessapi pull || git clone https://github.com/weddleben/pointlessapi.git

        # Publish
        dotnet publish -c Release -r linux-x64 -o /home/ec2-user/pointlessapi/publish

        # Move the published files
        sudo mkdir -p /var/www/pointless
        sudo cp -r /home/ec2-user/pointlessapi/publish/* /var/www/pointless/

        # Restart
        sudo systemctl restart pointless
